# permissions for end users to view resourcecleaners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourcecleaner-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubeswipe
    app.kubernetes.io/part-of: kubeswipe
    app.kubernetes.io/managed-by: kustomize
  name: resourcecleaner-viewer-role
rules:
- apiGroups:
  - kubeswipe.kubefit.com
  resources:
  - resourcecleaners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeswipe.kubefit.com
  resources:
  - resourcecleaners/status
  verbs:
  - get
